ignoreScripts: true
minimumReleaseAge: 5760
trustPolicy: no-downgrade
catalogMode: prefer
strictDepBuilds: true
blockExoticSubdeps: true

overrides:
  undici-types: 6.24.0

minimumReleaseAgeExclude:
  - "@ucdjs/*"

catalogs:
  dev:
    oxfmt: 0.43.0
    oxlint: 1.58.0
    oxlint-tsgolint: 0.19.0
    publint: 0.3.18
    tsdown: 0.21.7
    typescript: 6.0.2

  pipelines:
    "@ucdjs/pipelines-core": 0.0.1-beta.8
    "@ucdjs/cli": 0.3.1-beta.10

  types:
    "@types/node": 22.19.14
